pipeline {
    agent {
        label 'Dev'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "am building the image in the docker"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "am Testing the image in the docker"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "am Deploying the image in the kubernetes"'
            }
        }
        stage('cpudetails'){
            steps{
                sh '''
                    lscpu
                '''
            }
        }
    }
}